version: '3.8'

services:
  api:
    build:
      context: ./api
    ports:
      - "8080:8080"

  broker:
    build:
      context: ./broker
    ports:
      - "8081:8081"

  mail_service:
    build:
      context: ./mail_service
    ports:
      - "8082:8082"